export const GET_SUPPLIERS = "GET_SUPPLIERS";
export const LOAD_SUPPLIER = "LOAD_SUPPLIER";
export const FAIL_SUPPLIERS = "FAIL_SUPPLIERS";
export const GET_SUPPLIER = "GET_SUPPLIER";
export const FAIL_SUPPLIER = "FAIL_SUPPLIER";
